# Generated by Django 3.1 on 2020-11-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201123_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
