# Generated by Django 3.1 on 2020-11-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201123_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='slot',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot1',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot2',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot3',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot4',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot5',
            field=models.TimeField(null=True),
        ),
    ]
