# Generated by Django 3.1 on 2020-11-23 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201123_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(default=datetime.date(2020, 11, 23)),
        ),
    ]
