# Generated by Django 3.1 on 2020-11-23 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(default=datetime.date(2020, 11, 23)),
        ),
    ]
