# Generated by Django 3.1 on 2020-11-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_tempappointments_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempAppointments',
        ),
    ]
