# Generated by Django 3.1 on 2020-11-23 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_tempappointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAppointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField()),
                ('slot', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('disease', models.ManyToManyField(to='users.Disease')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
