# Generated by Django 3.1 on 2020-11-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_tempappointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='tempappointments',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='tempappointments',
            name='prescription',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
