# Generated by Django 3.1 on 2020-11-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20201123_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='slot',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot4',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot5',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tempappointments',
            name='slot',
            field=models.DateTimeField(),
        ),
    ]
